name: Build Extension

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]  # Updated to more recent Node version

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Check code formatting
      run: npm run lint
      continue-on-error: true  # Don't fail the build if linting fails
    
    - name: Build Extension
      run: npm run build
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: reddit-content-extractor
        path: |
          dist/
          !dist/**/*.map
    
    - name: Create release ZIP
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      run: |
        cd dist
        zip -r ../reddit-content-extractor.zip *
    
    - name: Upload release ZIP
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      uses: actions/upload-artifact@v4
      with:
        name: reddit-content-extractor-zip
        path: reddit-content-extractor.zip
    